# Generated by Django 5.2.18 on 2026-10-08 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_inventory_procurement_foundation'),
        ('pos', '0001_pos_room_service_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConsumptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_key', models.CharField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending recipe consumption'), ('PROCESSED', 'Stock consumption posted'), ('SKIPPED', 'No controlled recipe'), ('FAILED', 'Needs inventory review')], db_index=True, default='PENDING', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('pos_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_consumption_request', to='pos.posorder')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_consumption_requests_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='inventory_s_status_9899ae_idx')],
            },
        ),
    ]
