# Generated by Django 5.2.18 on 2026-10-08 00:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_count_controls'),
        ('pos', '0001_pos_room_service_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconsumptionrequest',
            name='resolution_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StockRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('tracking_mode', models.CharField(choices=[('COMPONENTS', 'Consume component stock'), ('NO_STOCK', 'Explicitly non-stock tracked')], default='COMPONENTS', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_recipes_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_recipes', to='inventory.stocklocation')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_recipes', to='pos.menuitem')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_recipes_retired', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['menu_item_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='StockRecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_menu_unit', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='inventory.stockitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stockrecipe')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StockConsumptionRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSED', 'Consumption posted'), ('SKIPPED', 'Explicitly non-stock'), ('FAILED', 'Recipe processing failed')], db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_consumption_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.stockconsumptionrequest')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='inventory_s_request_340ed0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockrecipe',
            index=models.Index(fields=['menu_item', 'is_active', '-version'], name='inventory_s_menu_it_8d90a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockrecipe',
            constraint=models.UniqueConstraint(fields=('menu_item', 'version'), name='one_recipe_version_per_menu_item'),
        ),
        migrations.AddConstraint(
            model_name='stockrecipeline',
            constraint=models.UniqueConstraint(fields=('recipe', 'item'), name='one_stock_item_per_recipe'),
        ),
    ]
