# Generated by Django 5.2.18 on 2026-10-07 23:16

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_report_range_indexes'),
        ('rooms', '0002_roomimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=56, unique=True)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('IN_HOUSE', 'In house'), ('CHECKED_OUT', 'Checked out'), ('NO_SHOW', 'No show'), ('CANCELLED', 'Cancelled')], db_index=True, default='EXPECTED', max_length=20)),
                ('expected_arrival', models.DateField()),
                ('expected_departure', models.DateField()),
                ('business_date', models.DateField(db_index=True, default=apps.core.utils.hotel_today)),
                ('actual_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stay', to='bookings.booking')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays_checked_out', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='bookings.guest')),
            ],
            options={
                'ordering': ['-business_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('ROOM_ASSIGNED', 'Room assigned'), ('ROOM_RELEASED', 'Room released'), ('NO_SHOW', 'No show'), ('CORRECTED', 'Corrected')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_events', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='stays.stay')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StayRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actual_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assignment_reason', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_rooms_assigned', to=settings.AUTH_USER_MODEL)),
                ('booking_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_rooms', to='bookings.bookingroom')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_occupancies', to='rooms.room')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_rooms', to='stays.stay')),
            ],
            options={
                'ordering': ['assigned_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['status', 'business_date'], name='stays_stay_status_071c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['guest', 'status'], name='stays_stay_guest_i_523f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['expected_departure', 'status'], name='stays_stay_expecte_d424dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.CheckConstraint(condition=models.Q(('expected_departure__gt', models.F('expected_arrival'))), name='stay_departure_after_arrival'),
        ),
        migrations.AddIndex(
            model_name='stayevent',
            index=models.Index(fields=['stay', 'occurred_at'], name='stays_staye_stay_id_895f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='stayroom',
            index=models.Index(fields=['stay', 'released_at'], name='stays_stayr_stay_id_81fc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='stayroom',
            index=models.Index(fields=['room', 'released_at'], name='stays_stayr_room_id_110a39_idx'),
        ),
    ]
