# Generated by Django 5.2.17 on 2026-09-09 07:18

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Price per night in hotel currency (NGN).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('bed_type', models.CharField(blank=True, default='', max_length=80)),
                ('bed_count', models.PositiveSmallIntegerField(default=1)),
                ('room_size', models.CharField(blank=True, default='', help_text='e.g. "25 m²"', max_length=60)),
                ('view', models.CharField(blank=True, default='', max_length=80)),
                ('smoking_policy', models.CharField(choices=[('NON_SMOKING', 'Non-smoking'), ('SMOKING_ALLOWED', 'Smoking allowed')], default='NON_SMOKING', max_length=20)),
                ('children_allowed', models.BooleanField(default=True)),
                ('extra_guest_allowed', models.BooleanField(default=False)),
                ('extra_guest_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per extra guest, per night.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='rooms.amenity')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='room-types/%Y/%m/', validators=[apps.core.validators.validate_image_upload])),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under maintenance'), ('OUT_OF_SERVICE', 'Out of service')], db_index=True, default='AVAILABLE', max_length=20)),
                ('housekeeping_status', models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('CLEANING', 'Being cleaned')], default='CLEAN', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['room_type', 'status'], name='rooms_room_room_ty_a51164_idx')],
            },
        ),
    ]
