# Generated by Django 5.2.17 on 2026-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_guest_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-supplied idempotency key for safe retries of booking creation.', max_length=64, null=True, unique=True),
        ),
    ]
