# Generated by Django 5.2.18 on 2026-10-07 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_idempotency_key'),
        ('offers', '0002_guestdiscount_guestdiscountapplication_and_more'),
        ('rooms', '0002_roomimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['cancelled_at'], name='bookings_bo_cancell_5850fc_idx'),
        ),
    ]
