# Generated by Django 5.2.18 on 2026-10-07 23:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_services', '0001_guest_service_requests'),
        ('rooms', '0002_roomimage'),
        ('stays', '0001_stay_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('type', models.CharField(choices=[('CHECKOUT_CLEAN', 'Checkout clean'), ('STAYOVER_SERVICE', 'Stayover service'), ('TURNDOWN', 'Turndown'), ('INSPECTION', 'Inspection'), ('GUEST_REQUEST', 'Guest request'), ('DEEP_CLEAN', 'Deep clean')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('READY_FOR_INSPECTION', 'Ready for inspection'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_inspection_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks_inspected', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housekeeping_tasks', to='rooms.room')),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='housekeeping_task', to='guest_services.servicerequest')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='housekeeping_tasks', to='stays.stay')),
            ],
            options={
                'ordering': ['due_at', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('CLAIMED', 'Claimed'), ('STATUS_CHANGED', 'Status changed'), ('COMMENT', 'Comment'), ('INSPECTED', 'Inspected')], db_index=True, max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_task_events', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='housekeeping.housekeepingtask')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['status', 'assigned_to', 'due_at'], name='housekeepin_status_15686a_idx'),
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['room', 'status'], name='housekeepin_room_id_aada97_idx'),
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['stay', 'created_at'], name='housekeepin_stay_id_7b4a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='housekeepingtaskevent',
            index=models.Index(fields=['task', 'created_at'], name='housekeepin_task_id_f64fa4_idx'),
        ),
    ]
