# Generated by Django 5.2.17 on 2026-09-09 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOOKING_CREATED', 'New booking'), ('BOOKING_CONFIRMED', 'Booking confirmed'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('BOOKING_MODIFIED', 'Booking modified'), ('PAYMENT_SUCCESS', 'Payment received'), ('PAYMENT_FAILED', 'Payment failed'), ('CHECK_IN', 'Guest checked in'), ('CHECK_OUT', 'Guest checked out'), ('ENQUIRY_NEW', 'New enquiry'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
