# Generated by Django 5.2.17 on 2026-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'New booking'), ('BOOKING_CONFIRMED', 'Booking confirmed'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('BOOKING_MODIFIED', 'Booking modified'), ('PAYMENT_SUCCESS', 'Payment received'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYMENT_REFUNDED', 'Payment refunded'), ('PAYMENT_DISPUTED', 'Payment disputed'), ('CHECK_IN', 'Guest checked in'), ('CHECK_OUT', 'Guest checked out'), ('ENQUIRY_NEW', 'New enquiry'), ('SYSTEM', 'System')], db_index=True, max_length=30),
        ),
    ]
