# Generated by Django 6.1.1 on 2026-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_cancellation_refund_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'New booking'), ('BOOKING_CONFIRMED', 'Booking confirmed'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('BOOKING_MODIFIED', 'Booking modified'), ('CANCELLATION_REQUEST_CREATED', 'Cancellation request created'), ('CANCELLATION_REQUEST_REVIEWED', 'Cancellation request reviewed'), ('CANCELLATION_REQUEST_APPROVED', 'Cancellation request approved'), ('CANCELLATION_REQUEST_REJECTED', 'Cancellation request rejected'), ('PAYMENT_SUCCESS', 'Payment received'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYMENT_REFUNDED', 'Payment refunded'), ('PAYMENT_DISPUTED', 'Payment disputed'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_PENDING', 'Refund pending'), ('REFUND_PROCESSING', 'Refund processing'), ('REFUND_PROCESSED', 'Refund processed'), ('REFUND_FAILED', 'Refund failed'), ('REFUND_NEEDS_ATTENTION', 'Refund needs attention'), ('CHECK_IN', 'Guest checked in'), ('CHECK_OUT', 'Guest checked out'), ('CHECKOUT_DUE_SOON', 'Checkout due soon'), ('CHECKOUT_AUTO', 'Automatic checkout'), ('ENQUIRY_NEW', 'New enquiry'), ('REVIEW_NEW', 'New customer review'), ('SYSTEM', 'System')], db_index=True, max_length=40),
        ),
    ]
