# Generated by Django 5.2.17 on 2026-09-15 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('RECEIPT', 'Payment receipt'), ('BOOKING_CONFIRMATION', 'Booking confirmation'), ('BOOKING_PENDING', 'Booking pending / complete payment'), ('CANCELLATION', 'Cancellation'), ('REFUND', 'Refund'), ('PASSWORD_RESET', 'Password reset'), ('ENQUIRY', 'Enquiry / staff alert'), ('REVIEW_INVITE', 'Review invitation'), ('GENERIC', 'Generic')], db_index=True, default='GENERIC', max_length=32)),
                ('booking_reference', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('booking_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attach_receipt_pdf', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=12)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_class', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='notificatio_kind_277426_idx'), models.Index(fields=['booking_reference', 'status'], name='notificatio_booking_f7f340_idx')],
            },
        ),
    ]
