# Generated by Django 5.2.17 on 2026-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
