# Generated by Django 5.2.17 on 2026-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_emaillog_html_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='failure_stage',
            field=models.CharField(blank=True, choices=[('', '—'), ('RENDER', 'Rendering the receipt'), ('ATTACHMENT', 'Generating the PDF attachment'), ('SMTP', 'Submitting to the mail server')], default='', max_length=16),
        ),
    ]
