# Generated by Django 5.2.17 on 2026-09-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_emaillog_failure_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='failure_stage',
            field=models.CharField(blank=True, choices=[('', '—'), ('RENDER', 'Rendering the receipt'), ('ATTACHMENT', 'Generating the PDF attachment'), ('SMTP', 'Submitting to the mail server')], db_default='', default='', max_length=16),
        ),
    ]
