# Generated by Django 5.2.18 on 2026-10-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_emaillog_synchronous_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('RECEIPT', 'Payment receipt'), ('BOOKING_CONFIRMATION', 'Booking confirmation'), ('BOOKING_PENDING', 'Booking pending / complete payment'), ('CANCELLATION', 'Cancellation'), ('REFUND', 'Refund'), ('PASSWORD_RESET', 'Password reset'), ('ENQUIRY', 'Enquiry / staff alert'), ('PORTAL_INVITATION', 'Guest portal invitation'), ('REVIEW_INVITE', 'Review invitation'), ('GENERIC', 'Generic')], db_index=True, default='GENERIC', max_length=32),
        ),
    ]
