# Generated by Django 5.2.18 on 2026-10-07 23:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_report_range_indexes'),
        ('rooms', '0002_roomimage'),
        ('stays', '0001_stay_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('category', models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('ROOM_SERVICE', 'Room service'), ('AMENITY', 'Amenity / supplies'), ('TRANSPORT', 'Transport'), ('BILLING', 'Billing / folio'), ('GENERAL', 'General assistance')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=12)),
                ('channel', models.CharField(choices=[('PORTAL', 'Guest portal'), ('FRONT_DESK', 'Front desk'), ('PHONE', 'Phone'), ('IN_PERSON', 'In person'), ('STAFF', 'Staff created')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('ESCALATED', 'Escalated')], db_index=True, default='OPEN', max_length=20)),
                ('owner_team', models.CharField(choices=[('FRONT_DESK', 'Front desk'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('FOOD_BEVERAGE', 'Food & beverage'), ('MANAGEMENT', 'Management')], db_index=True, default='FRONT_DESK', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('portal_email', models.EmailField(blank=True, default='', max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='bookings.guest')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='rooms.room')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='stays.stay')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('ACKNOWLEDGED', 'Acknowledged'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status changed'), ('COMMENT', 'Comment'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=20)),
                ('actor_label', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField(blank=True, default='')),
                ('guest_visible', models.BooleanField(db_index=True, default=False)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='guest_services.servicerequest')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'assigned_to', 'due_at'], name='guest_servi_status_8a733f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['owner_team', 'status', 'due_at'], name='guest_servi_owner_t_e97d50_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['stay', 'created_at'], name='guest_servi_stay_id_491cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['room', 'status'], name='guest_servi_room_id_43fa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['guest', 'created_at'], name='guest_servi_guest_i_420678_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestevent',
            index=models.Index(fields=['request', 'created_at'], name='guest_servi_request_ea862a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestevent',
            index=models.Index(fields=['request', 'guest_visible', 'created_at'], name='guest_servi_request_2516fa_idx'),
        ),
    ]
