# Generated by Django 5.2.18 on 2026-10-08 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_report_range_indexes'),
        ('guest_services', '0001_guest_service_requests'),
        ('rooms', '0002_roomimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='table_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('ROOM_SERVICE', 'Room service'), ('FOOD_BEVERAGE', 'Food & beverage service'), ('AMENITY', 'Amenity / supplies'), ('TRANSPORT', 'Transport'), ('BILLING', 'Billing / folio'), ('GENERAL', 'General assistance')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='channel',
            field=models.CharField(choices=[('PORTAL', 'Guest portal'), ('QR', 'Room / table QR'), ('FRONT_DESK', 'Front desk'), ('PHONE', 'Phone'), ('IN_PERSON', 'In person'), ('STAFF', 'Staff created')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='bookings.guest'),
        ),
        migrations.CreateModel(
            name='ServiceQRLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=48, unique=True)),
                ('target_key', models.CharField(editable=False, max_length=128, unique=True)),
                ('target_type', models.CharField(choices=[('ROOM', 'Guest room'), ('TABLE', 'Restaurant / bar table')], db_index=True, max_length=12)),
                ('table_number', models.CharField(blank=True, default='', max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_qr_links_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_qr_links', to='rooms.room')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_qr_links_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_type', 'label', 'reference'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='qr_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='guest_services.serviceqrlink'),
        ),
        migrations.AddIndex(
            model_name='serviceqrlink',
            index=models.Index(fields=['is_active', 'target_type', 'updated_at'], name='guest_servi_is_acti_b1b206_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceqrlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('room__isnull', False), ('table_number', ''), ('target_type', 'ROOM')), models.Q(('room__isnull', True), ('target_type', 'TABLE'), models.Q(('table_number', ''), _negated=True)), _connector='OR'), name='service_qr_target_shape'),
        ),
    ]
