# Generated by Django 5.2.18 on 2026-10-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_services', '0002_servicerequest_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestevent',
            name='type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACKNOWLEDGED', 'Acknowledged'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status changed'), ('COMMENT', 'Comment'), ('POS_ORDER_LINKED', 'POS draft linked'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=20),
        ),
    ]
