# Generated by Django 5.2.18 on 2026-10-09 06:44

import apps.guest_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_services', '0003_alter_servicerequestevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceqrlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, default=apps.guest_services.models._default_service_qr_expiry, null=True),
        ),
    ]
