# Generated by Django 5.2.17 on 2026-09-09 07:18

import apps.core.validators
import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/%Y/%m/', validators=[apps.core.validators.validate_image_upload])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hotel policies',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='J-ONE HOTEL & LODGE', max_length=150)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(default='Plot 566 Mgbowo Street, off Ezike Street', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('phone', models.CharField(default='+234803 211 2874', max_length=30)),
                ('email', models.EmailField(default='jonathanonu76@gmail.com', max_length=254)),
                ('google_maps_url', models.URLField(blank=True, default='')),
                ('social_links', models.JSONField(blank=True, default=list, help_text='List of {"platform": "facebook", "url": "https://..."} entries.')),
                ('check_in_time', models.TimeField(default=datetime.time(14, 0))),
                ('check_out_time', models.TimeField(default=datetime.time(12, 0))),
                ('min_stay_nights', models.PositiveSmallIntegerField(default=1)),
                ('max_stay_nights', models.PositiveSmallIntegerField(default=30)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat fee applied once per booking.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of the total required to confirm a booking online.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('pending_booking_minutes', models.PositiveIntegerField(default=15, help_text='How long an unpaid pending booking holds inventory.')),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=48, help_text='Guests may cancel up to this many hours before check-in.')),
                ('cancellation_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel settings',
                'verbose_name_plural': 'Hotel settings',
            },
        ),
    ]
