# Generated by Django 6.1.1 on 2026-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='google_review_url',
            field=models.URLField(blank=True, default='', help_text="Direct 'write a review' link for the hotel's Google Business profile. Leave blank to hide the Google review button."),
        ),
    ]
