# Generated by Django 5.2.17 on 2026-09-16 20:46

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelsettings_google_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='contact_image',
            field=models.ImageField(blank=True, help_text='Optional image shown on the public contact page.', null=True, upload_to='site/contact/', validators=[apps.core.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='experience_image',
            field=models.ImageField(blank=True, help_text='Custom homepage experience-section image (falls back to the built-in one).', null=True, upload_to='site/experience/', validators=[apps.core.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Custom homepage hero image. Replaces the built-in hero slideshow when set.', null=True, upload_to='site/hero/', validators=[apps.core.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='intro_image',
            field=models.ImageField(blank=True, help_text='Custom homepage welcome-section image (falls back to the built-in one).', null=True, upload_to='site/intro/', validators=[apps.core.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='location_image',
            field=models.ImageField(blank=True, help_text='Custom homepage location-section image (falls back to the built-in one).', null=True, upload_to='site/location/', validators=[apps.core.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='policy_image',
            field=models.ImageField(blank=True, help_text='Optional image shown at the top of the public policies page.', null=True, upload_to='site/policy/', validators=[apps.core.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='policy_text',
            field=models.TextField(blank=True, default='', help_text='Optional custom hotel policy (plain text). Leave empty to keep the existing policy documents.'),
        ),
    ]
