# Generated by Django 6.1.1 on 2026-09-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelsettings_contact_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelsettings',
            name='contact_image',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='experience_image',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='intro_image',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='location_image',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='policy_image',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='policy_text',
        ),
    ]
