# Generated by Django 5.2.17 on 2026-09-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_hotelsettings_contact_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='restrict_check_in_to_booked_date',
            field=models.BooleanField(default=True, help_text='Block check-in before the booked check-in date. Late arrivals inside the booked date range are always allowed.'),
        ),
    ]
