# Generated by Django 5.2.18 on 2026-10-07 23:19

import apps.core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from datetime import date
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_default_financial_control_policy(apps, schema_editor):
    """Install a conservative effective-dated baseline without overwriting edits."""
    policy = apps.get_model("finance", "FinancialControlPolicy")
    policy.objects.get_or_create(
        name="Default financial controls",
        defaults={
            "effective_from": date(1970, 1, 1),
            "is_active": True,
            "require_separate_approver": True,
            # Zero means every positive refund/discount requires approval until
            # management configures a different threshold. Collections do not
            # enter this approval path, preserving normal authorized speed.
            "refund_manager_approval_threshold": Decimal("0.00"),
            "discount_manager_approval_threshold": Decimal("0.00"),
            "cash_variance_manager_approval_threshold": Decimal("1000.00"),
            "notes": "Conservative initial finance control policy.",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_report_range_indexes'),
        ('payments', '0004_report_range_indexes'),
        ('stays', '0001_stay_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('business_date', models.DateField(db_index=True, default=apps.core.utils.hotel_today)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('terminal', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING_REVIEW', 'Pending variance review'), ('CLOSED', 'Closed'), ('VOIDED', 'Voided')], db_index=True, default='OPEN', max_length=20)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('review_approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_opened', to=settings.AUTH_USER_MODEL)),
                ('review_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_session_variances_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialControlPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('effective_from', models.DateField(db_index=True, default=apps.core.utils.hotel_today)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('require_separate_approver', models.BooleanField(default=True)),
                ('refund_manager_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_manager_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_variance_manager_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
                'indexes': [models.Index(fields=['is_active', 'effective_from'], name='finance_fin_is_acti_77ba46_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type', models.CharField(choices=[('REFUND', 'Refund'), ('DISCOUNT', 'Discount'), ('VOID', 'Void'), ('CASH_VARIANCE', 'Cash variance'), ('ADJUSTMENT', 'Adjustment'), ('EXPENSE', 'Expense')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('reason', models.TextField(blank=True, default='')),
                ('review_note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approval_reviews', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='finance.financialcontrolpolicy')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type', models.CharField(choices=[('ACCOMMODATION_CHARGE', 'Accommodation charge'), ('POS_CHARGE', 'POS / room-service charge'), ('OTHER_CHARGE', 'Other guest charge'), ('PAYMENT_COLLECTION', 'Payment collection'), ('REFUND', 'Refund'), ('DISCOUNT', 'Discount'), ('VOID', 'Void / reversal'), ('EXPENSE', 'Expense'), ('CASH_OPEN', 'Cash drawer opening'), ('CASH_CLOSE', 'Cash drawer closing'), ('CASH_MOVEMENT', 'Cash movement'), ('ADJUSTMENT', 'Controlled adjustment')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided by reversal')], db_index=True, default='DRAFT', max_length=12)),
                ('business_date', models.DateField(db_index=True, default=apps.core.utils.hotel_today)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('source_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('narrative', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions_initiated', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['-business_date', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('POSTED', 'Posted'), ('APPROVED', 'Approved'), ('REVERSED', 'Reversed'), ('ALLOCATED', 'Allocated'), ('CASH_SESSION_OPENED', 'Cash session opened'), ('CASH_SESSION_CLOSED', 'Cash session closed')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_events', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.approvalrequest')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.cashsession')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], db_index=True, default='DRAFT', max_length=20)),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('incurred_on', models.DateField(db_index=True, default=apps.core.utils.hotel_today)),
                ('payee', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_reference', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_requested', to=settings.AUTH_USER_MODEL)),
                ('financial_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['-incurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OPENING_FLOAT', 'Opening float'), ('COLLECTION', 'Cash collection'), ('REFUND', 'Cash refund'), ('PAID_OUT', 'Paid out'), ('SAFE_DROP', 'Safe drop'), ('CASH_IN', 'Cash in'), ('CASH_OUT', 'Cash out'), ('CLOSING_COUNT', 'Closing count')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.cashsession')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='finance.financialtransaction'),
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('MAIN', 'Main guest folio'), ('INCIDENTAL', 'Incidental folio'), ('GROUP', 'Group/master folio'), ('HOUSE', 'House account')], db_index=True, default='MAIN', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ON_HOLD', 'On hold'), ('CLOSED', 'Closed'), ('VOIDED', 'Voided')], db_index=True, default='OPEN', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='bookings.booking')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios_closed', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='bookings.guest')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios_opened', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='stays.stay')),
            ],
            options={
                'ordering': ['-opened_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(db_index=True, max_length=64)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.financialtransaction')),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_lines', to='finance.folio')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='FolioPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CHARGE', 'Charge'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('DISCOUNT', 'Discount'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], db_index=True, max_length=20)),
                ('effect', models.CharField(choices=[('DEBIT', 'Increases guest balance'), ('CREDIT', 'Reduces guest balance')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('business_date', models.DateField(db_index=True, default=apps.core.utils.hotel_today)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='finance.folio')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio_posting', to='finance.financialline')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_postings', to='finance.folioposting')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_postings', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['business_date', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('source_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='finance.folio')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_allocations', to='payments.payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['cashier', 'status'], name='finance_cas_cashier_95e2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['business_date', 'status'], name='finance_cas_busines_b23a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['type', 'business_date', 'status'], name='finance_fin_type_5ef623_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['status', 'posted_at'], name='finance_fin_status_168033_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['source_reference', 'type'], name='finance_fin_source__cb8955_idx'),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['transaction', 'occurred_at'], name='finance_fin_transac_aae5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['approval_request', 'occurred_at'], name='finance_fin_approva_84eec5_idx'),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['cash_session', 'occurred_at'], name='finance_fin_cash_se_dff787_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'incurred_on'], name='finance_exp_status_2c111d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'incurred_on'], name='finance_exp_categor_65a2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['cash_session', 'occurred_at'], name='finance_cas_cash_se_89e556_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'type', 'created_at'], name='finance_app_status_362ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester', 'status'], name='finance_app_request_4edf53_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['stay', 'status'], name='finance_fol_stay_id_beb95f_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['booking', 'status'], name='finance_fol_booking_177a36_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['guest', 'status'], name='finance_fol_guest_i_d2348c_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['status', 'opened_at'], name='finance_fol_status_5e738e_idx'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.CheckConstraint(condition=models.Q(('stay__isnull', False), ('booking__isnull', False), _connector='OR'), name='folio_requires_stay_or_booking'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(fields=('stay', 'kind'), name='one_folio_kind_per_stay'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['folio', 'created_at'], name='finance_fin_folio_i_7ffa98_idx'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['account_code', 'created_at'], name='finance_fin_account_675902_idx'),
        ),
        migrations.AddIndex(
            model_name='folioposting',
            index=models.Index(fields=['folio', 'business_date', 'created_at'], name='finance_fol_folio_i_0734c1_idx'),
        ),
        migrations.AddIndex(
            model_name='folioposting',
            index=models.Index(fields=['transaction', 'kind'], name='finance_fol_transac_3f5c16_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['folio', 'created_at'], name='finance_pay_folio_i_cc5e56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'created_at'], name='finance_pay_payment_cb1794_idx'),
        ),
        migrations.RunPython(seed_default_financial_control_policy, migrations.RunPython.noop),
    ]
