# Generated by Django 5.2.18 on 2026-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_folio_finance_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='type',
            field=models.CharField(choices=[('ACCOMMODATION_CHARGE', 'Accommodation charge'), ('POS_CHARGE', 'POS / room-service charge'), ('OTHER_CHARGE', 'Other guest charge'), ('PAYMENT_COLLECTION', 'Payment collection'), ('PAYMENT_ALLOCATION', 'Apply payment to folio'), ('REFUND', 'Refund'), ('DISCOUNT', 'Discount'), ('VOID', 'Void / reversal'), ('EXPENSE', 'Expense'), ('CASH_OPEN', 'Cash drawer opening'), ('CASH_CLOSE', 'Cash drawer closing'), ('CASH_MOVEMENT', 'Cash movement'), ('ADJUSTMENT', 'Controlled adjustment')], db_index=True, max_length=30),
        ),
    ]
