# Generated by Django 5.2.18 on 2026-10-07 23:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_allocation_transaction_type'),
        ('payments', '0004_report_range_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source_key', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_applications', to='payments.payment')),
                ('payment_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_applications', to='finance.paymentallocation')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_applications', to='payments.refund')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_applications', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['payment', 'created_at'], name='finance_ref_payment_9c6fea_idx'), models.Index(fields=['refund', 'created_at'], name='finance_ref_refund__e6cbb5_idx'), models.Index(fields=['payment_allocation', 'created_at'], name='finance_ref_payment_34246c_idx')],
            },
        ),
    ]
