# Generated by Django 5.2.18 on 2026-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_refund_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='request_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
