# Generated by Django 5.2.18 on 2026-10-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financial_event_reviewed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialevent',
            name='type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('POSTED', 'Posted'), ('APPROVED', 'Approved'), ('REVIEWED', 'Reviewed'), ('REVERSED', 'Reversed'), ('ALLOCATED', 'Allocated'), ('CASH_SESSION_OPENED', 'Cash session opened'), ('CASH_SESSION_CLOSED', 'Cash session closed'), ('CASH_VARIANCE_REVIEWED', 'Cash variance reviewed')], db_index=True, max_length=30),
        ),
    ]
