# Generated by Django 5.2.18 on 2026-10-08 01:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_cash_variance_review_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted')], db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='accounting_class',
            field=models.CharField(choices=[('OPERATING', 'Operating expense'), ('INVENTORY', 'Inventory asset')], default='OPERATING', max_length=16),
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_request', to='finance.approvalrequest'),
        ),
        migrations.AddField(
            model_name='expense',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.cashsession'),
        ),
        migrations.AddField(
            model_name='expense',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash paid out'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card / terminal'), ('PAYABLE', 'Accounts payable')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['requested_by', 'status', 'created_at'], name='finance_exp_request_ccac06_idx'),
        ),
        migrations.AddField(
            model_name='expenseevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseevent',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.expense'),
        ),
        migrations.AddIndex(
            model_name='expenseevent',
            index=models.Index(fields=['expense', 'created_at'], name='finance_exp_expense_1f7e68_idx'),
        ),
    ]
