# Generated by Django 5.2.18 on 2026-10-08 01:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expense_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcontrolpolicy',
            name='expense_manager_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
