# Generated by Django 5.2.18 on 2026-10-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('finance', '0008_expense_approval_threshold')]

    operations = [
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['status', 'currency', 'business_date'], name='finance_fin_status_9ab54a_idx'),
        ),
    ]
