# Generated by Django 5.2.18 on 2026-10-08 00:53

import apps.core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('type', models.CharField(choices=[('ANNUAL', 'Annual'), ('SICK', 'Sick'), ('PERSONAL', 'Personal'), ('UNPAID', 'Unpaid'), ('OTHER', 'Other')], default='ANNUAL', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_note', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_cancelled', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request_events', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='staff_operations.leaverequest')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='SCHEDULED', max_length=16)),
                ('planned_start_at', models.DateTimeField(db_index=True)),
                ('planned_end_at', models.DateTimeField(db_index=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('actual_worked_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_assigned', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_cancelled', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planned_start_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('business_date', models.DateField(db_index=True, default=apps.core.utils.hotel_today)),
                ('status', models.CharField(choices=[('ON_DUTY', 'On duty'), ('ON_BREAK', 'On break'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception')], db_index=True, default='ON_DUTY', max_length=16)),
                ('clock_in_at', models.DateTimeField()),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('active_break_started_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_break_minutes', models.PositiveIntegerField(default=0)),
                ('worked_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(db_index=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_record', to='staff_operations.shiftassignment')),
            ],
            options={
                'ordering': ['-clock_in_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLOCK_IN', 'Clock in'), ('BREAK_STARTED', 'Break started'), ('BREAK_ENDED', 'Break ended'), ('CLOCK_OUT', 'Clock out')], db_index=True, max_length=20)),
                ('source_key', models.CharField(max_length=180, unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='staff_operations.attendancerecord')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='staff_operations.shiftassignment')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignment_events', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='staff_operations.shiftassignment')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('unpaid_break_minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['department', 'start_time', 'name'],
                'indexes': [models.Index(fields=['is_active', 'department'], name='staff_opera_is_acti_2560d2_idx')],
            },
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='staff_operations.shifttemplate'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
                ('employment_start', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff', 'status', 'start_date'], name='staff_opera_staff_i_4d1da9_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='staff_opera_status_03f0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequestevent',
            index=models.Index(fields=['leave_request', 'created_at'], name='staff_opera_leave_r_046ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['staff', 'status', 'last_event_at'], name='staff_opera_staff_i_6e8fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['business_date', 'status'], name='staff_opera_busines_ee79dd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['staff', 'occurred_at'], name='staff_opera_staff_i_b088dc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['shift', 'occurred_at'], name='staff_opera_shift_i_87c320_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentevent',
            index=models.Index(fields=['shift', 'created_at'], name='staff_opera_shift_i_7a18db_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['staff', 'status', 'planned_start_at'], name='staff_opera_staff_i_bb65a1_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['status', 'planned_start_at'], name='staff_opera_status_06d347_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['department', 'planned_start_at'], name='staff_opera_departm_81e385_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['employment_status', 'department'], name='staff_opera_employm_528951_idx'),
        ),
    ]
