# Generated by Django 5.2.18 on 2026-10-08 17:51

import apps.staff_operations.payroll_models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financialtransaction_type'),
        ('staff_operations', '0001_staff_operations_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, default=apps.staff_operations.payroll_models._new_payroll_reference, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('starts_on', models.DateField(db_index=True)),
                ('ends_on', models.DateField(db_index=True)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for review'), ('APPROVED', 'Approved / accrued'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], db_index=True, default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=1000)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer')], default='', max_length=20)),
                ('external_reference', models.CharField(blank=True, default='', max_length=160)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('accrual_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accrual', to='finance.financialtransaction')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='finance.cashsession')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_paid', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment', to='finance.financialtransaction')),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_run', to='staff_operations.payrollperiod')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved / accrued'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_events', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='staff_operations.payrollperiod')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StaffCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_terms_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_id', '-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, default='', max_length=40)),
                ('employee_name', models.CharField(max_length=201)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allowances', models.JSONField(blank=True, default=list)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deductions', models.JSONField(blank=True, default=list)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='staff_operations.payrollperiod')),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='staff_operations.staffcompensation')),
            ],
            options={
                'ordering': ['department', 'employee_name', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status', 'starts_on', 'ends_on'], name='staff_opera_status_0d1b45_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='payroll_period_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('total_gross__gte', Decimal('0.00')), ('total_deductions__gte', Decimal('0.00')), ('total_net__gte', Decimal('0.00'))), name='payroll_totals_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='payrollevent',
            index=models.Index(fields=['period', 'created_at'], name='staff_opera_period__8545b9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcompensation',
            index=models.Index(fields=['staff', 'effective_from'], name='staff_opera_staff_i_fbb5c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffcompensation',
            constraint=models.UniqueConstraint(fields=('staff', 'effective_from'), name='unique_compensation_effective_date'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['staff', 'period'], name='staff_opera_staff_i_b5aab8_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('period', 'staff'), name='unique_payroll_staff_per_run'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(('net_pay__lte', models.F('gross_pay'))), name='payroll_net_not_above_gross'),
        ),
    ]
