# Generated by Django 5.2.18 on 2026-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_operations', '0002_staffprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='idempotency_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
