# Generated by Django 5.2.18 on 2026-10-09 01:14

import apps.staff_operations.payroll_models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financialtransaction_type'),
        ('staff_operations', '0003_payrollperiod_idempotency_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollStatutoryRuleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollStatutoryRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, default=apps.staff_operations.payroll_models._new_rule_reference, max_length=64, unique=True)),
                ('jurisdiction', models.CharField(db_index=True, default='NG', max_length=2)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('effective_from', models.DateField(db_index=True)),
                ('paye_bands', models.JSONField(default=apps.staff_operations.payroll_models._default_nigeria_2026_bands)),
                ('minimum_wage_monthly', models.DecimalField(decimal_places=2, default=Decimal('70000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('employee_pension_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('employer_pension_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('rent_relief_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('rent_relief_cap', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('legal_basis', models.TextField()),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending legal/compliance review'), ('APPROVED', 'Approved for use'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='payrollperiod',
            name='payroll_totals_nonnegative',
        ),
        migrations.AddField(
            model_name='payrollline',
            name='employee_pension',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='employer_pension',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='housing_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='life_insurance_premium_claim',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='mortgage_interest_claim',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='nhf_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='nhis_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='paye_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='pensionable_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='rent_paid_attributable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='rent_relief',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='tax_claims',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='transport_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='total_employer_pension',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='total_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='minimum_wage_applicability_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='minimum_wage_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='pension_applicability_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='pension_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffcompensation',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollstatutoryruleevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_rule_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollstatutoryruleset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_rule_sets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollstatutoryruleset',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_rule_sets_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollstatutoryruleevent',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='staff_operations.payrollstatutoryruleset'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='statutory_rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='staff_operations.payrollstatutoryruleset'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('total_gross__gte', Decimal('0.00')), ('total_deductions__gte', Decimal('0.00')), ('total_net__gte', Decimal('0.00')), ('total_paye__gte', Decimal('0.00')), ('total_employer_pension__gte', Decimal('0.00'))), name='payroll_totals_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='payrollstatutoryruleset',
            index=models.Index(fields=['jurisdiction', 'currency', 'status', 'effective_from'], name='staff_opera_jurisdi_7b2df0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollstatutoryruleevent',
            index=models.Index(fields=['rule_set', 'created_at'], name='staff_opera_rule_se_f4ce05_idx'),
        ),
    ]
