# Generated by Django 5.2.18 on 2026-10-09 01:20

import apps.staff_operations.payroll_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_operations', '0004_payrollstatutoryruleevent_payrollstatutoryruleset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTaxIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, default=apps.staff_operations.payroll_models._new_tax_identity_reference, max_length=64, unique=True)),
                ('tax_id', models.CharField(max_length=64, unique=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('registered_on', models.DateField()),
                ('evidence_reference', models.CharField(max_length=160)),
                ('change_reported_on', models.DateField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_tax_identities_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_tax_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_id', '-effective_from', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='payrollline',
            name='tax_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='staff_operations.payrolltaxidentity'),
        ),
        migrations.AddIndex(
            model_name='payrolltaxidentity',
            index=models.Index(fields=['staff', 'effective_from'], name='staff_opera_staff_i_38a6f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrolltaxidentity',
            constraint=models.UniqueConstraint(fields=('staff', 'effective_from'), name='unique_payroll_tax_id_effective_date'),
        ),
    ]
