# Generated by Django 5.2.18 on 2026-10-09 01:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_operations', '0005_payrolltaxidentity_payrollline_tax_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='benefits_in_kind',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='taxable_benefits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='taxable_gross_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollstatutoryruleset',
            name='accommodation_income_cap_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='payrollstatutoryruleset',
            name='owned_asset_benefit_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
    ]
