# Generated by Django 5.2.18 on 2026-10-09 03:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
import hashlib
import json

from django.conf import settings
from django.db import migrations, models


def backfill_paid_salary_payments(apps, schema_editor):
    """Preserve existing run-level paid evidence as employee payment history."""
    alias = schema_editor.connection.alias
    PayrollLine = apps.get_model("staff_operations", "PayrollLine")
    PayrollSalaryPayment = apps.get_model("staff_operations", "PayrollSalaryPayment")
    lines = PayrollLine.objects.using(alias).filter(period__status="PAID").select_related(
        "period", "period__paid_by", "period__cash_session", "period__payment_transaction",
    ).order_by("pk")
    pending = []
    for line in lines.iterator(chunk_size=500):
        amount = Decimal(line.net_pay).quantize(Decimal("0.01"))
        if amount <= Decimal("0.00"):
            continue
        period = line.period
        payment_date = django.utils.timezone.localdate(period.paid_at) if period.paid_at else period.ends_on
        key = f"legacy-payroll-salary-payment:{period.reference}:{line.pk}"
        fingerprint_data = {
            "period": period.reference, "line_id": line.pk, "amount": str(amount),
            "method": period.payment_method or "", "external_reference": period.external_reference or "",
            "cash_session": period.cash_session.reference if period.cash_session_id else "",
            "payment_date": payment_date.isoformat(),
        }
        fingerprint = hashlib.sha256(
            json.dumps(fingerprint_data, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        notes = f"Imported from legacy full-run settlement {period.reference}."
        if period.payment_transaction_id is None:
            notes += " No linked finance transaction was present; reconcile before attempting a reversal."
        elif period.payment_transaction.status != "POSTED":
            notes += f" Linked finance transaction is {period.payment_transaction.status}; reconcile before attempting a reversal."
        if period.payment_method not in {"CASH", "BANK_TRANSFER"}:
            notes += " The legacy payment method was missing or unrecognized; reconcile before attempting a reversal."
        pending.append(PayrollSalaryPayment(
            reference=f"SAL-LEGACY-{line.pk}",
            idempotency_key=key,
            idempotency_fingerprint=fingerprint,
            line_id=line.pk,
            amount=amount,
            currency=period.currency,
            payment_date=payment_date,
            method=period.payment_method or "",
            external_reference=(period.external_reference or "")[:160],
            notes=notes,
            recorded_by_id=period.paid_by_id,
            financial_transaction_id=period.payment_transaction_id,
            cash_session_id=period.cash_session_id,
            is_legacy_import=True,
        ))
        if len(pending) >= 500:
            PayrollSalaryPayment.objects.using(alias).bulk_create(pending, batch_size=500, ignore_conflicts=True)
            pending.clear()
    if pending:
        PayrollSalaryPayment.objects.using(alias).bulk_create(pending, batch_size=500, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financialtransaction_type'),
        ('staff_operations', '0006_payrollline_benefits_in_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollevent',
            name='type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved / accrued'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('PAYMENT_RECORDED', 'Salary payment recorded'), ('PAYMENT_REVERSED', 'Salary payment reversed')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for review'), ('APPROVED', 'Approved / accrued'), ('PARTIALLY_PAID', 'Partially paid'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.CreateModel(
            name='PayrollSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('idempotency_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer')], max_length=20)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('evidence_reference', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('correction_reason', models.CharField(blank=True, default='', max_length=500)),
                ('is_legacy_import', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_salary_payments', to='finance.cashsession')),
                ('financial_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_salary_payments', to='finance.financialtransaction')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='staff_operations.payrollline')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salary_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='staff_operations.payrollsalarypayment')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at', '-pk'],
                'indexes': [models.Index(fields=['line', 'payment_date'], name='staff_opera_line_id_6e50da_idx'), models.Index(fields=['method', 'payment_date'], name='staff_opera_method_376679_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payroll_salary_payment_positive')],
            },
        ),
        # Intentionally irreversible: reverting this schema would delete new
        # payment/reversal history created after deployment.
        migrations.RunPython(backfill_paid_salary_payments),
    ]
