# Generated by Django 5.2.18 on 2026-10-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_operations', '0008_face_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('outcome', models.CharField(db_index=True, max_length=30)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('source_key', models.CharField(max_length=160, unique=True)),
                ('workstation_reference', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryWorkstationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workstation_reference', models.CharField(db_index=True, max_length=64)),
                ('credential_token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_workstation_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=12)),
                ('finger_position', models.CharField(choices=[('UNKNOWN', 'Unknown / unspecified'), ('RIGHT_THUMB', 'Right thumb'), ('RIGHT_INDEX', 'Right index'), ('RIGHT_MIDDLE', 'Right middle'), ('RIGHT_RING', 'Right ring'), ('RIGHT_LITTLE', 'Right little'), ('LEFT_THUMB', 'Left thumb'), ('LEFT_INDEX', 'Left index'), ('LEFT_MIDDLE', 'Left middle'), ('LEFT_RING', 'Left ring'), ('LEFT_LITTLE', 'Left little')], default='RIGHT_INDEX', max_length=20)),
                ('minutiae_data', models.JSONField(blank=True, default=list)),
                ('template_format', models.CharField(default='ISO_19794_2_MINUTIAE', max_length=40)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=200)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_template_decisions', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['staff', 'status'], name='fptpl_staff_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('staff',), name='one_active_fingerprint_template_per_staff')],
            },
        ),
    ]
