# Generated by Django 5.2.18 on 2026-10-07 23:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_services', '0001_guest_service_requests'),
        ('rooms', '0002_roomimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('category', models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('HVAC', 'HVAC'), ('FURNITURE', 'Furniture / fixtures'), ('SAFETY', 'Safety'), ('GENERAL', 'General maintenance')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('PENDING_PARTS', 'Pending parts'), ('READY_FOR_VERIFICATION', 'Ready for verification'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_assigned', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_completed', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_reported', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='rooms.room')),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_order', to='guest_services.servicerequest')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_triaged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('CLAIMED', 'Claimed'), ('STATUS_CHANGED', 'Status changed'), ('COMMENT', 'Comment'), ('OUTAGE_STARTED', 'Room outage started'), ('OUTAGE_CLEARED', 'Room outage cleared'), ('VERIFIED', 'Verified completed')], db_index=True, max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RoomOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLEARED', 'Cleared')], db_index=True, default='ACTIVE', max_length=12)),
                ('outage_status', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of service')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cleared_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_outages_cleared', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_outages_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_outages', to='rooms.room')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='room_outage', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['status', 'assigned_to', 'due_at'], name='maintenance_status_cfd353_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['room', 'status'], name='maintenance_room_id_ee8ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['category', 'status', 'due_at'], name='maintenance_categor_cb11fb_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['work_order', 'created_at'], name='maintenance_work_or_e85cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='roomoutage',
            index=models.Index(fields=['room', 'status'], name='maintenance_room_id_137a33_idx'),
        ),
    ]
