# Generated by Django 5.2.18 on 2026-10-07 23:14

import django.db.models.deletion
from django.db import migrations, models


# Keep this migration self-contained. Capability codes are security contracts;
# later source edits must never silently rewrite a historical migration's seed.
CAPABILITIES = (
    ("account.view", "View staff accounts", "Identity", "View permitted staff account information."),
    ("account.manage", "Manage staff accounts", "Identity", "Create and change staff roles/accounts."),
    ("booking.read", "View reservations", "Reservations", "Read reservation and guest operational details."),
    ("booking.manage", "Manage reservations", "Reservations", "Create and manage permitted reservations."),
    ("stay.check_in", "Check in guests", "Stays", "Perform a validated guest check-in."),
    ("stay.check_out", "Check out guests", "Stays", "Perform a validated guest check-out."),
    ("folio.view", "View folios", "Finance", "View permitted guest folios and balances."),
    ("folio.charge.post", "Post normal folio charges", "Finance", "Post permitted normal charges to an open folio."),
    ("payment.capture", "Capture collections", "Finance", "Record permitted tender collections."),
    ("payment.refund.request", "Request refunds", "Finance", "Request a refund, void, or controlled discount."),
    ("payment.refund.approve", "Approve sensitive money actions", "Finance", "Approve policy-controlled refunds, voids, and discounts."),
    ("cash_session.open", "Open cash sessions", "Cashier", "Open the user's permitted cash session."),
    ("cash_session.close", "Close cash sessions", "Cashier", "Close the user's permitted cash session."),
    ("pos.order.manage", "Manage POS orders", "POS", "Create and progress permitted POS or room-service orders."),
    ("guest_request.manage", "Manage guest requests", "Guest services", "Create, assign, or progress permitted guest requests."),
    ("housekeeping.task.manage", "Manage housekeeping tasks", "Operations", "Work permitted housekeeping tasks."),
    ("maintenance.work_order.manage", "Manage maintenance work orders", "Operations", "Work permitted maintenance orders."),
    ("inventory.manage", "Manage inventory", "Inventory", "Create permitted inventory movements and counts."),
    ("procurement.manage", "Manage procurement", "Inventory", "Create and receive permitted procurement records."),
    ("reports.financial.view", "View financial reports", "Reports", "View financial reporting and exports."),
    ("audit.view", "View audit records", "Security", "View immutable audit history."),
    ("settings.manage", "Manage hotel settings", "Administration", "Manage hotel-wide configuration."),
)

ROLE_CODES = {
    "ADMIN": {row[0] for row in CAPABILITIES},
    "MANAGER": {
        "account.view", "booking.read", "booking.manage", "stay.check_in", "stay.check_out",
        "folio.view", "folio.charge.post", "payment.capture", "payment.refund.request",
        "payment.refund.approve", "cash_session.open", "cash_session.close", "pos.order.manage",
        "guest_request.manage", "housekeeping.task.manage", "maintenance.work_order.manage",
        "inventory.manage", "procurement.manage", "reports.financial.view", "audit.view",
    },
    "RECEPTIONIST": {
        "booking.read", "booking.manage", "stay.check_in", "stay.check_out", "folio.view",
        "folio.charge.post", "payment.capture", "payment.refund.request", "guest_request.manage",
    },
    "CASHIER": {
        "booking.read", "folio.view", "folio.charge.post", "payment.capture",
        "payment.refund.request", "cash_session.open", "cash_session.close", "pos.order.manage",
    },
    "HOUSEKEEPING": {"booking.read", "housekeeping.task.manage", "guest_request.manage"},
    "MAINTENANCE": {"booking.read", "maintenance.work_order.manage", "guest_request.manage"},
    "INVENTORY_CLERK": {"inventory.manage", "procurement.manage"},
}


def seed_capabilities(apps, schema_editor):
    Capability = apps.get_model("accounts", "Capability")
    RoleCapability = apps.get_model("accounts", "RoleCapability")
    by_code = {}
    for code, name, category, description in CAPABILITIES:
        capability, _ = Capability.objects.update_or_create(
            code=code,
            defaults={"name": name, "category": category, "description": description, "is_active": True},
        )
        by_code[code] = capability
    for role, codes in ROLE_CODES.items():
        for code in codes:
            RoleCapability.objects.get_or_create(role=role, capability=by_code[code])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(db_index=True, max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('INVENTORY_CLERK', 'Inventory Clerk'), ('GUEST', 'Guest')], db_index=True, default='RECEPTIONIST', max_length=20),
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('INVENTORY_CLERK', 'Inventory Clerk'), ('GUEST', 'Guest')], db_index=True, max_length=20)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_grants', to='accounts.capability')),
            ],
            options={
                'ordering': ['role', 'capability__code'],
                'constraints': [models.UniqueConstraint(fields=('role', 'capability'), name='unique_role_capability_grant')],
            },
        ),
        migrations.RunPython(seed_capabilities, migrations.RunPython.noop),
    ]
