# Generated by Django 5.2.18 on 2026-10-08 17:51

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_expense_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecapability',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('INVENTORY_CLERK', 'Inventory Clerk'), ('FRONT_DESK_SUPERVISOR', 'Front Desk Supervisor'), ('GENERAL_MANAGER', 'General Manager'), ('RESTAURANT_MANAGER', 'Restaurant Manager'), ('WAITER', 'Waiter / Server'), ('BAR_MANAGER', 'Bar Manager'), ('BARTENDER', 'Bartender'), ('KITCHEN_MANAGER', 'Kitchen Manager'), ('CHEF', 'Chef / Kitchen Staff'), ('HOUSEKEEPING_MANAGER', 'Housekeeping Manager'), ('HOUSEKEEPER', 'Housekeeper'), ('MAINTENANCE_TECHNICIAN', 'Maintenance Technician'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('ACCOUNTANT', 'Accountant'), ('HR_MANAGER', 'HR Manager'), ('SECURITY', 'Security'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('STOREKEEPER', 'Storekeeper'), ('GUEST', 'Guest')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('INVENTORY_CLERK', 'Inventory Clerk'), ('FRONT_DESK_SUPERVISOR', 'Front Desk Supervisor'), ('GENERAL_MANAGER', 'General Manager'), ('RESTAURANT_MANAGER', 'Restaurant Manager'), ('WAITER', 'Waiter / Server'), ('BAR_MANAGER', 'Bar Manager'), ('BARTENDER', 'Bartender'), ('KITCHEN_MANAGER', 'Kitchen Manager'), ('CHEF', 'Chef / Kitchen Staff'), ('HOUSEKEEPING_MANAGER', 'Housekeeping Manager'), ('HOUSEKEEPER', 'Housekeeper'), ('MAINTENANCE_TECHNICIAN', 'Maintenance Technician'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('ACCOUNTANT', 'Accountant'), ('HR_MANAGER', 'HR Manager'), ('SECURITY', 'Security'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('STOREKEEPER', 'Storekeeper'), ('GUEST', 'Guest')], db_index=True, default='RECEPTIONIST', max_length=32),
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.accounts.models._new_workstation_reference, editable=False, max_length=48, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('SHARED', 'Shared'), ('FRONT_DESK', 'Front desk'), ('RESTAURANT', 'Restaurant'), ('BAR', 'Bar'), ('KITCHEN', 'Kitchen'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('ACCOUNTS', 'Accounts'), ('INVENTORY', 'Inventory / stores'), ('HR', 'Human resources'), ('SECURITY', 'Security'), ('MANAGEMENT', 'Management')], db_index=True, default='SHARED', max_length=24)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations_created', to=settings.AUTH_USER_MODEL)),
                ('current_staff', models.ForeignKey(blank=True, help_text='Informational account reported by this client; not verified session ownership.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_current_workstations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'name', 'pk'],
                'indexes': [models.Index(fields=['is_active', 'department'], name='accounts_wo_is_acti_f2b853_idx')],
            },
        ),
    ]
