"""Seed verified department capabilities and least-privilege role grants."""
from django.db import migrations

# Frozen security-catalog snapshot. Do not import the live catalogue here:
# historical migrations must remain stable as product roles evolve.
CAPABILITIES = (('account.view', 'View staff accounts', 'Identity', 'View permitted staff account information.'),
 ('account.manage', 'Manage staff accounts', 'Identity', 'Create and change staff roles/accounts.'),
 ('booking.read', 'View reservations', 'Reservations', 'Read reservation and guest operational details.'),
 ('booking.manage', 'Manage reservations', 'Reservations', 'Create and manage permitted reservations.'),
 ('stay.check_in', 'Check in guests', 'Stays', 'Perform a validated guest check-in.'),
 ('stay.check_out', 'Check out guests', 'Stays', 'Perform a validated guest check-out.'),
 ('folio.view', 'View folios', 'Finance', 'View permitted guest folios and balances.'),
 ('folio.charge.post',
  'Post normal folio charges',
  'Finance',
  'Post permitted normal charges to an open folio.'),
 ('finance.controls.manage',
  'Manage finance controls',
  'Finance',
  'Create effective-dated financial control policies.'),
 ('payment.capture', 'Capture collections', 'Finance', 'Record permitted tender collections.'),
 ('payment.refund.request', 'Request refunds', 'Finance', 'Request a refund, void, or controlled discount.'),
 ('payment.refund.approve',
  'Approve sensitive money actions',
  'Finance',
  'Approve policy-controlled refunds, voids, and discounts.'),
 ('cash_session.open', 'Open cash sessions', 'Cashier', "Open the user's permitted cash session."),
 ('cash_session.close', 'Close cash sessions', 'Cashier', "Close the user's permitted cash session."),
 ('expense.manage', 'Manage expenses', 'Finance', 'Create, submit, and post permitted expense records.'),
 ('expense.approve',
  'Approve expenses',
  'Finance',
  'Independently approve or reject controlled expense requests.'),
 ('pos.order.manage',
  'Manage general POS orders',
  'POS',
  'Manage permitted room-service, restaurant, takeaway, and order records.'),
 ('pos.menu.manage', 'Manage POS menu', 'POS', 'Create and manage POS categories, items, and modifiers.'),
 ('restaurant.order.manage',
  'Manage restaurant orders',
  'Restaurant',
  'Create and progress restaurant orders.'),
 ('restaurant.table.manage',
  'Manage restaurant tables',
  'Restaurant',
  'Maintain table records and table-service sessions.'),
 ('bar.order.manage', 'Manage bar orders', 'Bar', 'Create and progress bar orders.'),
 ('bar.menu.manage', 'Manage bar menu', 'Bar', 'Maintain bar-category menu items.'),
 ('kitchen.queue.view',
  'View production queues',
  'Kitchen',
  "View the user's assigned kitchen or bar production queue."),
 ('kitchen.ticket.manage',
  'Progress production tickets',
  'Kitchen',
  'Start, mark ready, or complete assigned production tickets.'),
 ('guest_request.manage',
  'Manage guest requests',
  'Guest services',
  'Create or progress permitted guest requests.'),
 ('guest_request.assign',
  'Dispatch guest requests',
  'Guest services',
  'Assign or re-route guest service requests.'),
 ('housekeeping.task.manage',
  'Manage housekeeping tasks',
  'Operations',
  'Work permitted housekeeping tasks.'),
 ('housekeeping.task.assign',
  'Dispatch housekeeping tasks',
  'Operations',
  'Assign and inspect housekeeping tasks.'),
 ('maintenance.work_order.manage',
  'Manage maintenance work orders',
  'Operations',
  'Work permitted maintenance orders.'),
 ('maintenance.work_order.assign',
  'Dispatch maintenance work orders',
  'Operations',
  'Assign and verify maintenance work orders.'),
 ('inventory.manage', 'Manage inventory', 'Inventory', 'Create permitted inventory movements and counts.'),
 ('inventory.adjust.approve',
  'Approve inventory adjustments',
  'Inventory',
  'Approve count variances before stock adjustments post.'),
 ('procurement.manage',
  'Manage procurement',
  'Inventory',
  'Create and receive permitted procurement records.'),
 ('procurement.approve',
  'Approve procurement',
  'Inventory',
  'Approve purchase orders requested by another user.'),
 ('staff.profile.manage',
  'Manage staff operational profiles',
  'Staff operations',
  'Create and maintain non-sensitive staff operational profiles.'),
 ('shift.manage', 'Manage staff shifts', 'Staff operations', 'Create, schedule, and cancel staff shifts.'),
 ('attendance.clock',
  'Clock attendance',
  'Staff operations',
  "Record the user's own source-keyed attendance events."),
 ('attendance.manage',
  'Manage attendance',
  'Staff operations',
  'View workforce attendance records and resolve permitted operations.'),
 ('leave.request',
  'Request leave',
  'Staff operations',
  "Submit and cancel the user's permitted leave requests."),
 ('leave.approve', 'Approve leave', 'Staff operations', 'Review leave requests for other staff members.'),
 ('payroll.view', 'View payroll', 'Payroll', 'View payroll run and compensation records.'),
 ('payroll.manage', 'Prepare payroll', 'Payroll', 'Maintain compensation records and prepare payroll runs.'),
 ('payroll.approve', 'Approve payroll', 'Payroll', 'Independently approve a submitted payroll run.'),
 ('reports.financial.view', 'View financial reports', 'Reports', 'View financial reporting and exports.'),
 ('audit.view', 'View audit records', 'Security', 'View immutable audit history.'),
 ('terminal.manage',
  'Manage workstation registry',
  'Security',
  'Register, label, and deactivate informational workstations.'),
 ('service_qr.manage',
  'Manage guest service QR links',
  'Guest services',
  'Create and revoke signed room/table service links.'),
 ('settings.manage', 'Manage hotel settings', 'Administration', 'Manage hotel-wide configuration.'))

ROLE_CODES = {'ADMIN': ('account.manage',
           'account.view',
           'attendance.clock',
           'attendance.manage',
           'audit.view',
           'bar.menu.manage',
           'bar.order.manage',
           'booking.manage',
           'booking.read',
           'cash_session.close',
           'cash_session.open',
           'expense.approve',
           'expense.manage',
           'finance.controls.manage',
           'folio.charge.post',
           'folio.view',
           'guest_request.assign',
           'guest_request.manage',
           'housekeeping.task.assign',
           'housekeeping.task.manage',
           'inventory.adjust.approve',
           'inventory.manage',
           'kitchen.queue.view',
           'kitchen.ticket.manage',
           'leave.approve',
           'leave.request',
           'maintenance.work_order.assign',
           'maintenance.work_order.manage',
           'payment.capture',
           'payment.refund.approve',
           'payment.refund.request',
           'payroll.approve',
           'payroll.manage',
           'payroll.view',
           'pos.menu.manage',
           'pos.order.manage',
           'procurement.approve',
           'procurement.manage',
           'reports.financial.view',
           'restaurant.order.manage',
           'restaurant.table.manage',
           'service_qr.manage',
           'settings.manage',
           'shift.manage',
           'staff.profile.manage',
           'stay.check_in',
           'stay.check_out',
           'terminal.manage'),
 'MANAGER': ('account.view',
             'attendance.clock',
             'attendance.manage',
             'audit.view',
             'bar.menu.manage',
             'bar.order.manage',
             'booking.manage',
             'booking.read',
             'cash_session.close',
             'cash_session.open',
             'expense.approve',
             'expense.manage',
             'finance.controls.manage',
             'folio.charge.post',
             'folio.view',
             'guest_request.assign',
             'guest_request.manage',
             'housekeeping.task.assign',
             'housekeeping.task.manage',
             'inventory.adjust.approve',
             'inventory.manage',
             'kitchen.queue.view',
             'kitchen.ticket.manage',
             'leave.approve',
             'leave.request',
             'maintenance.work_order.assign',
             'maintenance.work_order.manage',
             'payment.capture',
             'payment.refund.approve',
             'payment.refund.request',
             'payroll.approve',
             'payroll.manage',
             'payroll.view',
             'pos.menu.manage',
             'pos.order.manage',
             'procurement.approve',
             'procurement.manage',
             'reports.financial.view',
             'restaurant.order.manage',
             'restaurant.table.manage',
             'service_qr.manage',
             'shift.manage',
             'staff.profile.manage',
             'stay.check_in',
             'stay.check_out',
             'terminal.manage'),
 'RECEPTIONIST': ('attendance.clock',
                  'booking.manage',
                  'booking.read',
                  'folio.charge.post',
                  'folio.view',
                  'guest_request.assign',
                  'guest_request.manage',
                  'housekeeping.task.assign',
                  'housekeeping.task.manage',
                  'leave.request',
                  'maintenance.work_order.assign',
                  'maintenance.work_order.manage',
                  'payment.capture',
                  'payment.refund.request',
                  'stay.check_in',
                  'stay.check_out'),
 'CASHIER': ('attendance.clock',
             'booking.read',
             'cash_session.close',
             'cash_session.open',
             'expense.manage',
             'folio.charge.post',
             'leave.request',
             'payment.capture',
             'payment.refund.request',
             'pos.order.manage'),
 'HOUSEKEEPING': ('attendance.clock',
                  'booking.read',
                  'guest_request.manage',
                  'housekeeping.task.manage',
                  'leave.request'),
 'MAINTENANCE': ('attendance.clock',
                 'booking.read',
                 'guest_request.manage',
                 'leave.request',
                 'maintenance.work_order.manage'),
 'INVENTORY_CLERK': ('attendance.clock', 'inventory.manage', 'leave.request', 'procurement.manage'),
 'FRONT_DESK_SUPERVISOR': ('attendance.clock',
                           'attendance.manage',
                           'booking.manage',
                           'booking.read',
                           'folio.charge.post',
                           'folio.view',
                           'guest_request.assign',
                           'guest_request.manage',
                           'housekeeping.task.assign',
                           'housekeeping.task.manage',
                           'leave.request',
                           'maintenance.work_order.assign',
                           'maintenance.work_order.manage',
                           'payment.capture',
                           'payment.refund.request',
                           'stay.check_in',
                           'stay.check_out'),
 'GENERAL_MANAGER': ('account.view',
                     'attendance.clock',
                     'attendance.manage',
                     'audit.view',
                     'bar.menu.manage',
                     'bar.order.manage',
                     'booking.manage',
                     'booking.read',
                     'cash_session.close',
                     'cash_session.open',
                     'expense.approve',
                     'expense.manage',
                     'finance.controls.manage',
                     'folio.charge.post',
                     'folio.view',
                     'guest_request.assign',
                     'guest_request.manage',
                     'housekeeping.task.assign',
                     'housekeeping.task.manage',
                     'inventory.adjust.approve',
                     'inventory.manage',
                     'kitchen.queue.view',
                     'kitchen.ticket.manage',
                     'leave.approve',
                     'leave.request',
                     'maintenance.work_order.assign',
                     'maintenance.work_order.manage',
                     'payment.capture',
                     'payment.refund.approve',
                     'payment.refund.request',
                     'payroll.approve',
                     'payroll.manage',
                     'payroll.view',
                     'pos.menu.manage',
                     'pos.order.manage',
                     'procurement.approve',
                     'procurement.manage',
                     'reports.financial.view',
                     'restaurant.order.manage',
                     'restaurant.table.manage',
                     'service_qr.manage',
                     'shift.manage',
                     'staff.profile.manage',
                     'stay.check_in',
                     'stay.check_out',
                     'terminal.manage'),
 'RESTAURANT_MANAGER': ('attendance.clock',
                        'attendance.manage',
                        'kitchen.queue.view',
                        'leave.request',
                        'payment.capture',
                        'pos.menu.manage',
                        'restaurant.order.manage',
                        'restaurant.table.manage',
                        'shift.manage'),
 'WAITER': ('attendance.clock',
            'guest_request.manage',
            'leave.request',
            'payment.capture',
            'restaurant.order.manage'),
 'BAR_MANAGER': ('attendance.clock',
                 'attendance.manage',
                 'bar.menu.manage',
                 'bar.order.manage',
                 'kitchen.queue.view',
                 'leave.request',
                 'payment.capture',
                 'shift.manage'),
 'BARTENDER': ('attendance.clock',
               'bar.order.manage',
               'guest_request.manage',
               'leave.request',
               'payment.capture'),
 'KITCHEN_MANAGER': ('attendance.clock',
                     'attendance.manage',
                     'kitchen.queue.view',
                     'kitchen.ticket.manage',
                     'leave.request',
                     'shift.manage'),
 'CHEF': ('attendance.clock', 'kitchen.queue.view', 'kitchen.ticket.manage', 'leave.request'),
 'HOUSEKEEPING_MANAGER': ('attendance.clock',
                          'attendance.manage',
                          'guest_request.assign',
                          'guest_request.manage',
                          'housekeeping.task.assign',
                          'housekeeping.task.manage',
                          'leave.request',
                          'shift.manage'),
 'HOUSEKEEPER': ('attendance.clock', 'guest_request.manage', 'housekeeping.task.manage', 'leave.request'),
 'MAINTENANCE_TECHNICIAN': ('attendance.clock',
                            'guest_request.manage',
                            'leave.request',
                            'maintenance.work_order.manage'),
 'ACCOUNTS_MANAGER': ('account.view',
                      'audit.view',
                      'cash_session.close',
                      'cash_session.open',
                      'expense.approve',
                      'expense.manage',
                      'finance.controls.manage',
                      'folio.charge.post',
                      'folio.view',
                      'payment.capture',
                      'payment.refund.approve',
                      'payment.refund.request',
                      'payroll.approve',
                      'payroll.manage',
                      'payroll.view',
                      'reports.financial.view'),
 'ACCOUNTANT': ('attendance.clock',
                'expense.manage',
                'folio.charge.post',
                'folio.view',
                'leave.request',
                'payment.capture',
                'payment.refund.request',
                'payroll.manage',
                'payroll.view',
                'reports.financial.view'),
 'HR_MANAGER': ('attendance.clock',
                'attendance.manage',
                'leave.approve',
                'leave.request',
                'payroll.approve',
                'payroll.manage',
                'payroll.view',
                'shift.manage',
                'staff.profile.manage'),
 'SECURITY': ('attendance.clock', 'audit.view', 'guest_request.manage'),
 'PROCUREMENT_OFFICER': ('attendance.clock', 'leave.request', 'procurement.manage'),
 'STOREKEEPER': ('attendance.clock', 'inventory.manage', 'leave.request', 'procurement.manage'),
 'GUEST': ()}


def seed_department_capabilities(apps, schema_editor):
    Capability = apps.get_model("accounts", "Capability")
    RoleCapability = apps.get_model("accounts", "RoleCapability")
    by_code = {}
    for code, name, category, description in CAPABILITIES:
        capability, _ = Capability.objects.update_or_create(
            code=code,
            defaults={"name": name, "category": category, "description": description, "is_active": True},
        )
        by_code[code] = capability
    for role, codes in ROLE_CODES.items():
        for code in codes:
            RoleCapability.objects.get_or_create(role=role, capability=by_code[code])


class Migration(migrations.Migration):
    dependencies = [("accounts", "0013_alter_rolecapability_role_alter_user_role_and_more")]
    operations = [migrations.RunPython(seed_department_capabilities, migrations.RunPython.noop)]
