# Generated by Django 5.2.18 on 2026-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_payroll_statutory_rule_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='sign_in_key_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workstation',
            name='sign_in_key_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
