# Generated by Django 5.2.17 on 2026-09-09 07:18

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', validators=[apps.core.validators.validate_image_upload])),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('HOTEL', 'Hotel'), ('ROOMS', 'Rooms'), ('RESTAURANT', 'Restaurant'), ('FACILITIES', 'Facilities'), ('EVENTS', 'Events'), ('EXTERIOR', 'Exterior'), ('OTHER', 'Other')], db_index=True, default='HOTEL', max_length=20)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
