# Generated by Django 5.2.18 on 2026-10-07 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccessChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Portal sign in')], default='LOGIN', max_length=30)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'expires_at'], name='portal_port_email_bba56d_idx'), models.Index(fields=['email', 'consumed_at'], name='portal_port_email_daa838_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('session_hash', models.CharField(max_length=64, unique=True)),
                ('authentication_method', models.CharField(choices=[('EMAIL_MAGIC_LINK', 'Verified email magic link')], default='EMAIL_MAGIC_LINK', max_length=40)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('device_label', models.CharField(blank=True, default='', max_length=120)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='portal.portalaccesschallenge')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['email', 'expires_at'], name='portal_port_email_fe9d0d_idx'), models.Index(fields=['email', 'revoked_at'], name='portal_port_email_aa7bf1_idx')],
            },
        ),
    ]
