# Generated by Django 5.2.18 on 2026-10-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_emaillog_synchronous_delivery'),
        ('portal', '0001_capability_and_portal_foundation'),
        ('stays', '0001_stay_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPortalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Not delivered'), ('NO_EMAIL', 'No email address on file')], db_index=True, default='PENDING', max_length=12)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=40)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_invitations', to='notifications.emaillog')),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_invitation', to='stays.stay')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'last_attempt_at'], name='portal_gues_status_2ca109_idx')],
            },
        ),
    ]
