# Generated by Django 5.2.18 on 2026-10-07 23:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_financial_event_reviewed_type'),
        ('stays', '0001_stay_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='pos_menucat_is_acti_ebf533_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=15)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pos.menucategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifiers', to='pos.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=96, null=True, unique=True)),
                ('mode', models.CharField(choices=[('ROOM_SERVICE', 'Room service'), ('RESTAURANT', 'Restaurant / dine in'), ('TAKEAWAY', 'Takeaway')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to kitchen'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered / served'), ('CANCELLED', 'Cancelled before delivery'), ('VOIDED', 'Voided by controlled reversal')], db_index=True, default='DRAFT', max_length=20)),
                ('settlement_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], db_index=True, default='NOT_APPLICABLE', max_length=20)),
                ('guest_name', models.CharField(blank=True, default='', max_length=200)),
                ('table_number', models.CharField(blank=True, default='', max_length=40)),
                ('delivery_location', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('charge_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_order_charge', to='finance.financialtransaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders_created', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='finance.folio')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='stays.stay')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_ticket', to='pos.posorder')),
            ],
            options={
                'ordering': ['-priority', 'queued_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PosOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('CHARGED', 'Charged to folio'), ('TENDER_CAPTURED', 'Tender captured'), ('VOID_REQUESTED', 'Void requested')], db_index=True, max_length=24)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='pos.posorder')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PosOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=180)),
                ('item_sku', models.CharField(blank=True, default='', max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('modifiers_snapshot', models.JSONField(blank=True, default=list)),
                ('modifier_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='pos.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='pos.posorder')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PosTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card / POS terminal'), ('BANK_TRANSFER', 'Bank transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CAPTURED', 'Captured'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_tenders_captured', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_tenders', to='finance.cashsession')),
                ('collection_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_tender_collection', to='finance.financialtransaction')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='pos.posorder')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_active', 'is_available'], name='pos_menuite_categor_b4aab4_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_active', 'is_available', 'sort_order'], name='pos_menuite_is_acti_a75c84_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_menu_item_name_per_category'),
        ),
        migrations.AddIndex(
            model_name='menumodifier',
            index=models.Index(fields=['menu_item', 'is_active'], name='pos_menumod_menu_it_ddf4c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='menumodifier',
            constraint=models.UniqueConstraint(fields=('menu_item', 'name'), name='unique_modifier_name_per_item'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['status', '-created_at'], name='pos_posorde_status_bb8f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['mode', 'status', '-created_at'], name='pos_posorde_mode_a47aec_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['stay', 'status'], name='pos_posorde_stay_id_2fcb95_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['folio', 'status'], name='pos_posorde_folio_i_505006_idx'),
        ),
        migrations.AddConstraint(
            model_name='posorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'ROOM_SERVICE'), _negated=True), models.Q(('stay__isnull', False), ('folio__isnull', False)), _connector='OR'), name='room_service_order_requires_stay_folio'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['status', 'priority', 'queued_at'], name='pos_kitchen_status_2e4cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='posorderevent',
            index=models.Index(fields=['order', 'occurred_at'], name='pos_posorde_order_i_8627b8_idx'),
        ),
        migrations.AddIndex(
            model_name='posorderline',
            index=models.Index(fields=['order', 'created_at'], name='pos_posorde_order_i_4b3ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='postender',
            index=models.Index(fields=['order', 'status'], name='pos_postend_order_i_660216_idx'),
        ),
        migrations.AddIndex(
            model_name='postender',
            index=models.Index(fields=['cash_session', 'status'], name='pos_postend_cash_se_63644e_idx'),
        ),
    ]
