# Generated by Django 5.2.18 on 2026-10-08 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_pos_room_service_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='station',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('BAR', 'Bar')], db_index=True, default='KITCHEN', max_length=16),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='service_area',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('BAR', 'Bar')], db_index=True, default='RESTAURANT', max_length=16),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='mode',
            field=models.CharField(choices=[('ROOM_SERVICE', 'Room service'), ('RESTAURANT', 'Restaurant / dine in'), ('BAR', 'Bar'), ('TAKEAWAY', 'Takeaway')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['station', 'status', 'queued_at'], name='pos_kitchen_station_741462_idx'),
        ),
    ]
