# Generated by Django 5.2.18 on 2026-10-08 20:43

import apps.pos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financialtransaction_type'),
        ('pos', '0002_kitchenticket_station_menucategory_service_area_and_more'),
        ('stays', '0001_stay_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTableSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OPENED', 'Opened'), ('ORDER_ADDED', 'POS order added'), ('CLOSED', 'Closed')], db_index=True, max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('section', models.CharField(blank=True, default='', max_length=80)),
                ('seats', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_tables_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_tables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, default=apps.pos.models._new_restaurant_table_session_reference, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=12)),
                ('covers', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=96, null=True, unique=True)),
                ('idempotency_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('close_note', models.CharField(blank=True, default='', max_length=500)),
                ('active_table', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_session', to='pos.restauranttable')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_table_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_table_sessions_opened', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.restauranttable')),
            ],
            options={
                'ordering': ['-opened_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='table_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.restauranttablesession'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['table_session', 'status'], name='pos_ord_tblsess_status_idx'),
        ),
        migrations.AddField(
            model_name='restauranttablesessionevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_table_session_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restauranttablesessionevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_session_events', to='pos.posorder'),
        ),
        migrations.AddField(
            model_name='restauranttablesessionevent',
            name='table_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='pos.restauranttablesession'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['is_active', 'section', 'code'], name='pos_restaur_is_acti_007d6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.CheckConstraint(condition=models.Q(('seats__gte', 1), ('seats__lte', 60)), name='restaurant_table_seats_range'),
        ),
        migrations.AddIndex(
            model_name='restauranttablesession',
            index=models.Index(fields=['status', 'opened_at'], name='pos_restaur_status_d86c72_idx'),
        ),
        migrations.AddIndex(
            model_name='restauranttablesession',
            index=models.Index(fields=['table', 'status'], name='pos_restaur_table_i_c45996_idx'),
        ),
        migrations.AddConstraint(
            model_name='restauranttablesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_table__isnull', False), ('closed_at__isnull', True), ('status', 'OPEN')), models.Q(('active_table__isnull', True), ('closed_at__isnull', False), ('status', 'CLOSED')), _connector='OR'), name='restaurant_table_session_state_fields'),
        ),
        migrations.AddConstraint(
            model_name='restauranttablesession',
            constraint=models.CheckConstraint(condition=models.Q(('covers__gte', 1), ('covers__lte', 60)), name='restaurant_table_session_covers_range'),
        ),
        migrations.AddIndex(
            model_name='restauranttablesessionevent',
            index=models.Index(fields=['table_session', 'occurred_at'], name='pos_restaur_table_s_6f7422_idx'),
        ),
    ]
