# Generated by Django 5.2.18 on 2026-10-08 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_services', '0003_alter_servicerequestevent_type'),
        ('pos', '0003_restauranttablesessionevent_restauranttable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_order', to='guest_services.servicerequest'),
        ),
    ]
