# Generated by Django 5.2.17 on 2026-09-09 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=60, unique=True)),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack (online)'), ('CASH', 'Cash'), ('POS', 'POS Terminal'), ('BANK_TRANSFER', 'Bank Transfer')], default='PAYSTACK', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('channel', models.CharField(blank=True, default='', max_length=40)),
                ('gateway_response', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(blank=True, help_text='Payer (online) or staff member who recorded the payment (offline).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx')],
            },
        ),
    ]
