# Generated by Django 5.2.18 on 2026-10-07 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_report_range_indexes'),
        ('payments', '0003_refund_cancellation_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payments_pa_status_bed4b8_idx'),
        ),
    ]
