/* ==========================================================================
   J-ONE HOTEL & LODGE — frontend version marker (GENERATED by build.py).

   This file is regenerated from version.json on every build; do not edit
   it by hand. js/update-checker.js compares window.JONE_VERSION against
   the live version.json to detect that a newer deployment is available.
   ========================================================================== */
window.JONE_VERSION = "1.1.11";
