# Generated by Django 5.2.17 on 2026-09-09 07:18

import apps.core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Optional promo code guests can enter (case-insensitive).', max_length=30, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('min_nights', models.PositiveSmallIntegerField(default=1)),
                ('max_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/%Y/%m/', validators=[apps.core.validators.validate_image_upload])),
                ('terms', models.TextField(blank=True, default='')),
                ('room_types', models.ManyToManyField(blank=True, related_name='offers', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-is_featured', '-start_date', 'title'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='offers_offe_is_acti_e6c4de_idx')],
            },
        ),
    ]
