# Generated by Django 5.2.17 on 2026-09-20 09:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_idempotency_key'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField(db_index=True, help_text='First date the discount may be applied to a booking.')),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='Optional expiry date (inclusive).', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(help_text='Why this guest was granted a discount (shown to staff only).', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created/approved this discount.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_discounts_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(help_text='The individual guest this discount belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='bookings.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestDiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Actual money taken off this booking.', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_discount_application', to='bookings.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='bookings.guest')),
                ('guest_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='offers.guestdiscount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guestdiscount',
            index=models.Index(fields=['guest', 'is_active'], name='offers_gues_guest_i_22e68d_idx'),
        ),
        migrations.AddIndex(
            model_name='guestdiscount',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='offers_gues_is_acti_0f707e_idx'),
        ),
        migrations.AddIndex(
            model_name='guestdiscountapplication',
            index=models.Index(fields=['guest', '-created_at'], name='offers_gues_guest_i_c34c84_idx'),
        ),
    ]
